spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  cache:
    type: none
  hazelcast:
    config: classpath:hazelcast.yaml
server:
  port: 8081


